### ISSUE TITLE
Bad predictions

### ISSUE THREAD

**Issue by ocacontrolroom** [araucaria-project/ctc#16]
Raport:
* telescope, 
* time/date, 
* sequence, 
* duration prediction (wrong)

jk15, 2024-11-26T14:38 UTC, ZERO test seq=1/u/0.0, 574s

--Mikolaj

**Comment by MMiirrkk** [comment]
Fixed! Now DARK, ZERO, SNAP should be ok. Ctc module is already updated on all computers: zenith, nadir, aux .
Please @majkelx give me some feedback if is ok in TOI now.

FYI: @astromg

**Comment by MMiirrkk** [comment]
Solved by use object parameters in other not trained well commands
